title: Jana Rutkowska # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Hi there, and welcome to my portfolio!  
  <br><br>
  I’m Jana, a data analyst with a passion for data visualizations, NLP, and all things related to language and AI.I started as a medical interpreter, helping patients who speak limited English access essential healthcare, which inspired the focus of my projects and my data career.
  <br><br>
  Explore my work, and thanks for stopping by!
  <br><br>
  <br><br>
  I'm always happy to connect! 
  <br><br>
  <a href="https://www.linkedin.com/in/jana-rutkowska-data-analyst/">LinkedIn</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/jana.rutkowska/vizzes">Tableau Public</a>
  <br><br>
  <a href="https://medium.com/@janarutkowska">Medium</a>
  

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
